# Generated by Django 5.2.5 on 2025-08-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_bhai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='addres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
