# Generated by Django 5.2.5 on 2025-08-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_bhai', '0002_alter_student_addres'),
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=50)),
                ('speed', models.IntegerField(default=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
